float time = Time;
float PI = 3.1415926535897932f;
float2 world_pos = Pos.xy;
float wave_height = WaveHeight;


float2 direction = {1.0, 0.0};
direction = normalize(direction);
float test = dot(world_pos, direction);

// float3 wave = 30.0f*sin(0.01*(PI*2/3)*direction*world_pos + time); 
float wave = wave_height*sin(0.01*(PI*2/48)*test + time); 
float height = wave;
return float3(0.0, 0.0, height);